### ISSUE TITLE
Set up github pages deploy

### ISSUE THREAD

**Issue by OmarShehata** [mplawley/tundra-tech-talks#1]
I pushed https://github.com/mplawley/tundra-tech-talks/commit/1d5e7fdd35d21529a7fec01e16e382ff05674f22 to set up deploying to github pages every time we push to `main`. It will build the website and push it to the `gh-pages` branch.

To finish deploy we just need to configure github pages to use `gh-pages`, but I don't have access to do this @mplawley 

![image](https://github.com/mplawley/tundra-tech-talks/assets/1711126/9a1965c7-34a9-467c-8d68-c87cb27fea95)

**Comment by mplawley** [comment]
Thank you, @OmarShehata! It looks like I have this set up correctly now, sir.
